# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UIDesign/v0.01_Connect.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DialogConnect(object):
    def setupUi(self, DialogConnect):
        DialogConnect.setObjectName("DialogConnect")
        DialogConnect.setWindowModality(QtCore.Qt.NonModal)
        DialogConnect.setEnabled(True)
        DialogConnect.resize(190, 90)
        DialogConnect.setMinimumSize(QtCore.QSize(190, 90))
        DialogConnect.setMaximumSize(QtCore.QSize(190, 90))
        DialogConnect.setBaseSize(QtCore.QSize(190, 80))
        self.layoutWidget = QtWidgets.QWidget(DialogConnect)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 171, 71))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.labelPortName = QtWidgets.QLabel(self.layoutWidget)
        self.labelPortName.setAlignment(QtCore.Qt.AlignCenter)
        self.labelPortName.setObjectName("labelPortName")
        self.gridLayout.addWidget(self.labelPortName, 0, 0, 1, 1)
        self.labelBaudRate = QtWidgets.QLabel(self.layoutWidget)
        self.labelBaudRate.setAlignment(QtCore.Qt.AlignCenter)
        self.labelBaudRate.setObjectName("labelBaudRate")
        self.gridLayout.addWidget(self.labelBaudRate, 0, 1, 1, 1)
        self.comboBoxPortName = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBoxPortName.setObjectName("comboBoxPortName")
        self.gridLayout.addWidget(self.comboBoxPortName, 1, 0, 1, 1)
        self.pushButtonConnect = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButtonConnect.setObjectName("pushButtonConnect")
        self.gridLayout.addWidget(self.pushButtonConnect, 2, 0, 1, 2)
        self.comboBoxBaudRate = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBoxBaudRate.setObjectName("comboBoxBaudRate")
        self.comboBoxBaudRate.addItem("")
        self.comboBoxBaudRate.addItem("")
        self.comboBoxBaudRate.addItem("")
        self.comboBoxBaudRate.addItem("")
        self.comboBoxBaudRate.addItem("")
        self.gridLayout.addWidget(self.comboBoxBaudRate, 1, 1, 1, 1)

        self.retranslateUi(DialogConnect)
        QtCore.QMetaObject.connectSlotsByName(DialogConnect)

    def retranslateUi(self, DialogConnect):
        _translate = QtCore.QCoreApplication.translate
        DialogConnect.setWindowTitle(_translate("DialogConnect", "Connect"))
        self.labelPortName.setText(_translate("DialogConnect", "Port name"))
        self.labelBaudRate.setText(_translate("DialogConnect", "Baud rate"))
        self.pushButtonConnect.setText(_translate("DialogConnect", "Connect"))
        self.comboBoxBaudRate.setItemText(0, _translate("DialogConnect", "115200"))
        self.comboBoxBaudRate.setItemText(1, _translate("DialogConnect", "57600"))
        self.comboBoxBaudRate.setItemText(2, _translate("DialogConnect", "38400"))
        self.comboBoxBaudRate.setItemText(3, _translate("DialogConnect", "19200"))
        self.comboBoxBaudRate.setItemText(4, _translate("DialogConnect", "9600"))
