# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UIDesign/v0.01_FeedRate.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DialogFeedRate(object):
    def setupUi(self, DialogFeedRate):
        DialogFeedRate.setObjectName("DialogFeedRate")
        DialogFeedRate.resize(495, 150)
        DialogFeedRate.setMinimumSize(QtCore.QSize(495, 150))
        DialogFeedRate.setMaximumSize(QtCore.QSize(495, 150))
        self.gridLayoutWidget = QtWidgets.QWidget(DialogFeedRate)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 477, 131))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.checkBoxEnableFeedRateCalculator = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBoxEnableFeedRateCalculator.setObjectName("checkBoxEnableFeedRateCalculator")
        self.gridLayout.addWidget(self.checkBoxEnableFeedRateCalculator, 0, 0, 1, 2)
        self.pushButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 0, 3, 1, 1)
        self.checkBoxTakeMinFeed = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBoxTakeMinFeed.setEnabled(False)
        self.checkBoxTakeMinFeed.setObjectName("checkBoxTakeMinFeed")
        self.gridLayout.addWidget(self.checkBoxTakeMinFeed, 1, 0, 2, 2)
        self.checkBoxTakeMaxFeed = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBoxTakeMaxFeed.setEnabled(False)
        self.checkBoxTakeMaxFeed.setObjectName("checkBoxTakeMaxFeed")
        self.gridLayout.addWidget(self.checkBoxTakeMaxFeed, 1, 2, 2, 2)
        self.labelMinFeed = QtWidgets.QLabel(self.gridLayoutWidget)
        self.labelMinFeed.setEnabled(False)
        self.labelMinFeed.setObjectName("labelMinFeed")
        self.gridLayout.addWidget(self.labelMinFeed, 3, 0, 2, 1)
        self.spinBoxMinFeed = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.spinBoxMinFeed.setEnabled(False)
        self.spinBoxMinFeed.setFrame(False)
        self.spinBoxMinFeed.setMinimum(1)
        self.spinBoxMinFeed.setMaximum(9999)
        self.spinBoxMinFeed.setObjectName("spinBoxMinFeed")
        self.gridLayout.addWidget(self.spinBoxMinFeed, 3, 1, 2, 1)
        self.labelMaxFeed = QtWidgets.QLabel(self.gridLayoutWidget)
        self.labelMaxFeed.setEnabled(False)
        self.labelMaxFeed.setObjectName("labelMaxFeed")
        self.gridLayout.addWidget(self.labelMaxFeed, 3, 2, 2, 1)
        self.spinBoxMaxFeed = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.spinBoxMaxFeed.setEnabled(False)
        self.spinBoxMaxFeed.setFrame(False)
        self.spinBoxMaxFeed.setMinimum(1)
        self.spinBoxMaxFeed.setMaximum(9999)
        self.spinBoxMaxFeed.setObjectName("spinBoxMaxFeed")
        self.gridLayout.addWidget(self.spinBoxMaxFeed, 3, 3, 2, 1)

        self.retranslateUi(DialogFeedRate)
        self.pushButton.clicked.connect(DialogFeedRate.accept)
        QtCore.QMetaObject.connectSlotsByName(DialogFeedRate)

    def retranslateUi(self, DialogFeedRate):
        _translate = QtCore.QCoreApplication.translate
        DialogFeedRate.setWindowTitle(_translate("DialogFeedRate", "Feed rate"))
        self.checkBoxEnableFeedRateCalculator.setText(_translate("DialogFeedRate", "Enable real time feed rate calculation"))
        self.pushButton.setText(_translate("DialogFeedRate", "Ok"))
        self.checkBoxTakeMinFeed.setText(_translate("DialogFeedRate", "Take min feed rate from file"))
        self.checkBoxTakeMaxFeed.setText(_translate("DialogFeedRate", "Take max feed rate from file"))
        self.labelMinFeed.setText(_translate("DialogFeedRate", "Min feed rate:"))
        self.labelMaxFeed.setText(_translate("DialogFeedRate", "Max feed rate:"))
