# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UIDesign/v0.01_General.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DialogGeneral(object):
    def setupUi(self, DialogGeneral):
        DialogGeneral.setObjectName("DialogGeneral")
        DialogGeneral.setEnabled(True)
        DialogGeneral.resize(250, 200)
        DialogGeneral.setMinimumSize(QtCore.QSize(250, 200))
        DialogGeneral.setMaximumSize(QtCore.QSize(250, 200))
        DialogGeneral.setBaseSize(QtCore.QSize(210, 217))
        self.gridLayout_2 = QtWidgets.QGridLayout(DialogGeneral)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.pushButtonOk = QtWidgets.QPushButton(DialogGeneral)
        self.pushButtonOk.setObjectName("pushButtonOk")
        self.gridLayout.addWidget(self.pushButtonOk, 4, 0, 1, 2)
        self.checkBoxAgresivePreload = QtWidgets.QCheckBox(DialogGeneral)
        self.checkBoxAgresivePreload.setObjectName("checkBoxAgresivePreload")
        self.gridLayout.addWidget(self.checkBoxAgresivePreload, 0, 0, 1, 2)
        self.labelSWaitToResponde = QtWidgets.QLabel(DialogGeneral)
        self.labelSWaitToResponde.setObjectName("labelSWaitToResponde")
        self.gridLayout.addWidget(self.labelSWaitToResponde, 2, 0, 1, 1)
        self.checkBoxWriteLogs = QtWidgets.QCheckBox(DialogGeneral)
        self.checkBoxWriteLogs.setObjectName("checkBoxWriteLogs")
        self.gridLayout.addWidget(self.checkBoxWriteLogs, 1, 0, 1, 2)
        self.spinBoxSWaitToResponse = QtWidgets.QSpinBox(DialogGeneral)
        self.spinBoxSWaitToResponse.setFrame(False)
        self.spinBoxSWaitToResponse.setMinimum(1)
        self.spinBoxSWaitToResponse.setMaximum(999)
        self.spinBoxSWaitToResponse.setProperty("value", 60)
        self.spinBoxSWaitToResponse.setObjectName("spinBoxSWaitToResponse")
        self.gridLayout.addWidget(self.spinBoxSWaitToResponse, 2, 1, 1, 1)
        self.doubleSpinBoxZJogRate = QtWidgets.QDoubleSpinBox(DialogGeneral)
        self.doubleSpinBoxZJogRate.setFrame(False)
        self.doubleSpinBoxZJogRate.setMinimum(0.01)
        self.doubleSpinBoxZJogRate.setMaximum(9999.99)
        self.doubleSpinBoxZJogRate.setSingleStep(0.01)
        self.doubleSpinBoxZJogRate.setProperty("value", 259.99)
        self.doubleSpinBoxZJogRate.setObjectName("doubleSpinBoxZJogRate")
        self.gridLayout.addWidget(self.doubleSpinBoxZJogRate, 3, 1, 1, 1)
        self.labelZJogRate = QtWidgets.QLabel(DialogGeneral)
        self.labelZJogRate.setObjectName("labelZJogRate")
        self.gridLayout.addWidget(self.labelZJogRate, 3, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)

        self.retranslateUi(DialogGeneral)
        self.pushButtonOk.clicked.connect(DialogGeneral.accept)
        QtCore.QMetaObject.connectSlotsByName(DialogGeneral)

    def retranslateUi(self, DialogGeneral):
        _translate = QtCore.QCoreApplication.translate
        DialogGeneral.setWindowTitle(_translate("DialogGeneral", "General"))
        self.pushButtonOk.setText(_translate("DialogGeneral", "Ok"))
        self.checkBoxAgresivePreload.setText(_translate("DialogGeneral", "Use agresive preload strategy for Grbl"))
        self.labelSWaitToResponde.setText(_translate("DialogGeneral", "Seconds wait to response:"))
        self.checkBoxWriteLogs.setText(_translate("DialogGeneral", "Write logs in txt file"))
        self.labelZJogRate.setText(_translate("DialogGeneral", "Z-Jog rate (mm/min):"))
